### ISSUE TITLE
Must be name 'acme' (lowercase)

### ISSUE THREAD

**Issue by strarsis** [maxhoesel/ansible-collection-smallstep#119]
The provisioner name for ACME must be in lowercase `acme`, otherwise step CA will not find the provisioner (`certbot` uses the lowercase variant).

```yml
    - name: Add ACME provisioner
      maxhoesel.smallstep.step_ca_provisioner:
        name: acme
        type: ACME
      become: yes
      become_user: "{{ step_ca_user }}"
````

Currently this is not the case in the `prepare.yml` file:
https://github.com/maxhoesel/ansible-collection-smallstep/blob/4e4e0a375db8fe76aebdf8210546a4001873a6b2/roles/step_acme_cert/molecule/default/prepare.yml#L24-L29

It may also be a good idea to add this to the README as an example for adding the ACME provisioner.
