### ISSUE TITLE
Defining `null` defaults for variables makes checking more difficult

### ISSUE THREAD

**Issue by eengstrom** [maxhoesel/ansible-collection-smallstep#20]
I sort of understand the reason to make sure that every variable has a default (`defaults/main.yml`), but in the case of defining variables with a `null` default, it makes checking for appropriate values more difficult.  As it stands now, if you don't define a value for either `stepca_root_password` or `stepca_intermediate_password`, the check for validity will fail, not with your defined failure message, but with a true error (`NoneType has no len()`).

I would suggest commenting out the definitions in `defaults/main.yml` and adding revising the assert clauses, as in:

```
- name: Check that passwords are set
  assert:
    that:
      - stepca_root_password is defined
      - stepca_root_password | length > 0
      - stepca_intermediate_password is defined
      - stepca_intermediate_password | length > 0
    fail_msg: "Please make sure that both stepca_root_password and stepca_intermediate_password are set!"
```

This actually makes it easier to conditionalize use of the role in my standard usage as well, with a `pre_task` such as:

```
  pre_tasks:
    # Allow this playbook to be run on ALL hosts,
    # BUT, skip everything unless required vars are defined for this host.
    - name: step-ca | End pla when insufficient variables defined
      meta: end_host
      when: stepca_root_password is defined
```
