### ISSUE TITLE
`step_ca` role throws error in check mode

### ISSUE THREAD

**Issue by Scronkfinkle** [maxhoesel/ansible-collection-smallstep#65]
While running in check mode, I am running across the following error:
```
TASK [maxhoesel.smallstep.step_ca : Set latest release version] [CHECK MODE] ******************************************************************************************************************
fatal: [steptest1]: FAILED! => {}

MSG:

The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'json'

The error appears to be in '/ansible/dev/collections/ansible_collections/maxhoesel/smallstep/roles/step_ca/tasks/main.yml': line 16, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

      delay: 5
    - name: Set latest release version
      ^ here
```

This appears to stem from the following block:
```
- block:
    - name: Get latest step-ca release information
      uri:
        url: https://api.github.com/repos/smallstep/certificates/releases/latest
        body_format: json
        return_content: yes
      register: step_ca_latest_release
      delegate_to: localhost
      become: no
      run_once: yes
      retries: 3
      delay: 5
    - name: Set latest release version
      set_fact:
        step_ca_version: "{{ (step_ca_latest_release.json.tag_name)[1:] }}"
  when: step_ca_version == 'latest'
```
adding `check_mode: no` under the `when:` appears to resolve the issue
